trigen_thank_homepage:
    path:     /{path}
    defaults: { _controller: TrigenThankBundle:Thank:index }
    requirements:
        path: (|follows|followers|user/.*|invite) 

trigen_thank_api:
    path:     /api
    defaults: { _controller: TrigenThankBundle:Thank:api }
    methods:  [GET, POST]

trigen_thank_preview:
    path:     /preview/{id}
    defaults: { _controller: TrigenThankBundle:Thank:preview }

trigen_thank_test_api:
    path:     /test-api
    defaults: { _controller: TrigenThankBundle:Thank:testApi }
    methods:  [GET, POST]
