<?php

namespace Trigen\Bundle\ThankBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ThankRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ThankRepository extends EntityRepository
{
}
