trigen_user_login:
    path:     /login
    defaults: { _controller: TrigenUserBundle:User:login }

trigen_user_verify:
    path:     /verify
    defaults: { _controller: TrigenUserBundle:User:verify }
    methods:  [GET, POST]
