services:
    trigen.thank_controller:
        class: Trigen\Bundle\ThankBundle\Controller\ThankController
        calls:
            - [setContainer, ["@service_container"]]

    trigen.aouth_user_provider:
        class: Trigen\Bundle\UserBundle\Entity\OAuthUserProvider
        arguments:
            - @doctrine

    trigen.user_listener:
        class: Trigen\Bundle\UserBundle\EventListener\UserListener
        arguments: 
            - @security.context
            - @router

        tags:
            # - { name: kernel.event_listener, event: kernel.response, method: onResponse }
            - { name: kernel.event_listener, event: kernel.request, method: onRequest }