parameters:
#    trigen_user.example.class: Trigen\Bundle\UserBundle\Example

services:
#    trigen_user.example:
#        class: %trigen_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

parameters:
    user_class_name: Trigen\Bundle\UserBundle\Entity\User

services:
    trigen.aouth_user_provider:
        class: Trigen\Bundle\UserBundle\Entity\OAuthUserProvider
        arguments:
            - @doctrine
            - %user_class_name%